apiVersion: v1
kind: Secret
metadata:
  name: aipclm-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: aipclm
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.credentials.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.credentials.password }}
  JWT_SECRET: {{ .Values.backend.jwtSecret }}
